

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Components/Navbar";
// import { Roboto } from 'next/font/google';

// const roboto = Roboto({
//   subsets: ['latin'],
//   weight: ['400', '700'],
// });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   <body className="bg-slate-900 text-white overflow-x-hidden">
        
      <Navbar/>
        <br />
        {children}
    


      </body>
    </html>
  );
}
