import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Components/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className="bg-slate-900 text-white"
      >
      <Navbar/>
        <br />
        {children}
    


      </body>
    </html>
  );
}
